version: '3'

services:
  avago:
    image: martineck/subsecond-blocktime
    container_name: avago
    network_mode: host
    volumes:
      - ~/.avalanchego:/root/.avalanchego
    environment:
      - AVAGO_PARTIAL_SYNC_PRIMARY_NETWORK=true
      - AVAGO_PUBLIC_IP_RESOLUTION_SERVICE=opendns
      - AVAGO_HTTP_HOST=0.0.0.0
      - AVAGO_TRACK_SUBNETS=${subnetId}
      - AVAGO_NETWORK_ID=fuji
      - AVAGO_HTTP_ALLOWED_HOSTS=*
      - AVAGO_PROPOSERVM_MIN_BLOCK_DELAY=600ms
    restart: unless-stopped
