services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.3
    container_name: clickhouse
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"  # HTTP
      - "9000:9000"  # Native TCP
    environment:
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD}"
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    volumes:
      - /data/clickhouse:/var/lib/clickhouse
      - /data/clickhouse/logs:/var/log/clickhouse-server