services:
  avago00:
    image: containerman17/subnet-evm-plus:latest
    container_name: avago00
    network_mode: host
    restart: always
    volumes:
      - ~/.avalanchego_00/:/root/.avalanchego
    environment:
      - AVAGO_PARTIAL_SYNC_PRIMARY_NETWORK=false
      - AVAGO_PUBLIC_IP_RESOLUTION_SERVICE=opendns
      - AVAGO_HTTP_HOST=0.0.0.0
      - AVAGO_HTTP_PORT=9002
      - AVAGO_STAKING_PORT=9003
      - AVAGO_TRACK_SUBNETS=qCccbQ4CJekniXpdgfdoFinEAkUf4wys9T89JNTK9CuvcMW81,2hBZBRc7SraKnT3AkPiCByYTFtWh6wKZViJ8QJpCjYhLyLCmQR,VsxF67NQTACc2fLQL9fD3F8LzJ5eezcSGFNitGsk7VxKbPwcD,25HsT5NZw5hrCZBgi7zqafWXyDqbU3yCV4xuA593qU54XQecy4,nWsbPVjZcdAYRkxPMDyNmDp5eBQCby5LwLu6KzC9VCjk4bp5j,23dqTMHK186m4Rzcn1ukJdmHy13nqido4LjTp5Kh9W6qBKaFib,3inyDoxM3Wksbxbo1oRXvxLKHyxK98XZYww5AknyapjfhQoRT,kf1sMrGJSA2x9yZfvjBJCHu3ZdTievrCyrbEEPKXbHMH2tXuA,WChFQ1twkXBLxZGo4qojC9AgizFrRdMRnPCK9FZmisY7z6pUs,2Dt7yXBvYHh6uqExB476ZTLWkVmaqzxkGSzCXxsRHMwDMVzw6m,QNCJ233aLWzubBViquKQCiY2JU2R6NDqUUwLtG6ax87S8UJCm,H8BEmxqhT23bEr9R6Cg5zfaXt1bKHLS9SzVeFo57FSqeZDu5Y,yD6k6gVKmzFbefPcdYjsJz17KVQFSivTR1emJ5cTBvq2d8MRg,5vcCHz5fgd1hWyXaKiLnMAVjmh4qW7yFxNbASBjxCXZYE445N,2LbGgyVZE5aMMYPp3h1F2MkKbjefR51nSZWaZzarDZf8GThCcX,2wKKYiv2EkZJKMoriJuqkcasEtLoqQk3fa3garx7PAGJojjMdn
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "3"
  avago01:
    image: containerman17/subnet-evm-plus:latest
    container_name: avago01
    network_mode: host
    restart: always
    volumes:
      - ~/.avalanchego_01/:/root/.avalanchego
    environment:
      - AVAGO_PARTIAL_SYNC_PRIMARY_NETWORK=true
      - AVAGO_PUBLIC_IP_RESOLUTION_SERVICE=opendns
      - AVAGO_HTTP_HOST=0.0.0.0
      - AVAGO_HTTP_PORT=9004
      - AVAGO_STAKING_PORT=9005
      - AVAGO_TRACK_SUBNETS=R2iSZc3NucxEtEbj7vEs42jf5zngTsjCEaUAqyEYYYGSmq3Jc,LXTDJCc8UPUcMpAmn958ExfTyzR5CRTNtTw8x175E4P7htoDH,h7egyVb6fKHMDpVaEsTEcy7YaEnXrayxZS4A1AEU4pyBzmwGp,2sF5Pb165jhdeNSy2kT4WyDYazu3buh1WGh77oTBA9dDjBPtsy,TfTBHvcxpBfxPntMpadskcZTH8AG5rgkrNyz2DzeByNMsZkMo,o4Eariv2Cx1fTvPFXYofpJfS9KgwFaiGN8KFGcCeZM9t87GJr,2ocjsdpN9czPYmHqS4Tc5Aydj4zk2WWVdX9jdXtqvMjQuf9pgV,6uH9zL2ZhPLWB1W1qodgRRm42YfLWdPKtQe2xzAWjr5TAhkmm,2TqrQau4E99KoUXcFjyf1Pek3rUHpDpqtN9rC5GDaCKFu7dfPo,hbP3PrnQS71Py1VVxvHfnCnr7MWos3XQesEsCKQoA9hpciyVR,2rQ8M43c9NTv1545VsTunmY95m8QLw8koNYawuTnMtDf97im99,2JzTHmoPJr1qSF1gTCirdKnVV913daTYmu33yyGucK4fqqXC5X,j6HXQWdpRhX7yHMWLehUyYDjypHa455vP5tuiXZ81nkPgveFV,dvqEJ3jJQmQ1N7ykvqq6TWyKu47q4yXmdZqaeMo6795GZmHUf,2LQHZFVXCLNwxn8aYbE5sbH5ALorbUWid7metpFqkwBKWcwhbf,jmLmezoViv3F72XLzpdmSNk3qLEGb72g5EYkp3ij4wHXPF2KN
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "3"
  avago02:
    image: containerman17/subnet-evm-plus:latest
    container_name: avago02
    network_mode: host
    restart: always
    volumes:
      - ~/.avalanchego_02/:/root/.avalanchego
    environment:
      - AVAGO_PARTIAL_SYNC_PRIMARY_NETWORK=true
      - AVAGO_PUBLIC_IP_RESOLUTION_SERVICE=opendns
      - AVAGO_HTTP_HOST=0.0.0.0
      - AVAGO_HTTP_PORT=9006
      - AVAGO_STAKING_PORT=9007
      - AVAGO_TRACK_SUBNETS=2LyJdHSdQDwg84nrbLrmtvEoAuudg41dWnhrbjMQUq78bdDHnT,pchqewRRQHwx1B3XJEq9p2HGSdjrHsyv48YzVUWXZbrmH4TM6,2ZKrfJUwXDsp27ggtxTqhWnzV87GpHppu2XJsv2nmFkHefHZZ5,B7hA9WibSJu2fKdHT2XZs2RYg1rZTtxwg6cMYBKYjvcJjbqsp,2Mi7V6HwKCEPxXTRG87o5tHACECkMPnJKP6UA3w1ote7j46GYT,2vL4TMT23mZzTsdkSSMFWZArFNWskR3xRWvCLxdrgd4rCe6vVy,2MbQjnTg3yxEtZBfnamboi7K9AajwNq7WExiwReBQSBtwbBVer,2MFMK4igZd3bL133TE8qao9QTKi56s2AK83yTL2hE9JYkZde5U,2H1TLFqf4y1rbcdC9R6iaospSLuDQVkjhYzZ5Vy2gCNGkubXqp,x1C95jnFyLV3x8tiiCW7ZFRoRFgq9SX1Yprwfxx4GCTujggYB,hqqtt4VGmzSACDn2yYxTFMhHu9RpFTECEhbexb4bXu2w6Pxtf,2np4VHz1c31SjmiMmtSZ27VswzDhKZThznVRXX9AzkD37BKfNx,2nCzBViQ5jxLaxkg9TABx6oXu1UGU7chM7G6XzPvW9ehP8RfrJ,2jSd7RdKVoqVQoUjuvJBuMPancYJ3CUcLLdqfu6RFocHyxxEQh,q54cgHa9RN2NFp9qsfpPzVkhgn8xqDgKEQR1G997xZ1P5Dc8o,63toLWYNBLvCZvYqRArcVo6jxv2PUPRWM39pRc34ffGTe2bPu
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "3"
  avago03:
    image: containerman17/subnet-evm-plus:latest
    container_name: avago03
    network_mode: host
    restart: always
    volumes:
      - ~/.avalanchego_03/:/root/.avalanchego
    environment:
      - AVAGO_PARTIAL_SYNC_PRIMARY_NETWORK=true
      - AVAGO_PUBLIC_IP_RESOLUTION_SERVICE=opendns
      - AVAGO_HTTP_HOST=0.0.0.0
      - AVAGO_HTTP_PORT=9008
      - AVAGO_STAKING_PORT=9009
      - AVAGO_TRACK_SUBNETS=2r7mmEKg3R2gTD22TtErn8KD8TmLeSjVXHdwMpH2S9BESUxH7q,2Y83BEXg7zgSCJunL2KD2i1vjMfaMnU1QEpG4M7acqG44BnRto,2eq3DtJp4cWzvGd8Q3ZFo8VpZmmD235Xoxgq6CmX8anZ69M54,gdZCkuVbt6QmTdgQ4z9Y3dcooTy12UuyFZq7bKs83TmvG5fAz,28NfaGpEddtjPESwKyjns6MJB91bvCHoAp3UsuY2PZWK2jrkxe,5moznRzaAEhzWkNTQVdT1U4Kb9EU7dbsKZQNmHwtN5MGVQRyT,GSkwV1pXkrm3f9e79f16x3PjJKHvBFDd5Fe1CSBWPEEQCJfTf,25Z5KLaGqNaUB5Gmo5BADwEDokTPJLvJJK3mNQCVUZmrvs9jYf,28E5rVqxKdZVzwP8LBm2v6EBFZJGtUBbVKZp3Y947Cmr2H7Pog,Cvoddysz7vrgicTjhiuFtEZ7FMzCVDDzwDv5Dd4XBrjAvnGK2,2PkFwku54MGMqUuwWwiEnt5pgWE51DHQW9hAePbsnPdxAbtiG,JYiYv9f6cRgsJNMACbd6fZGVvbxfN2R6NfVPHnvHBuP3vnDNb,2vbUo9xZZJ6wH1BZvzTA468EW9CjyytQ3xXawGCttUBmeinjqY,d4yfvAkTtX8PhSSfCCD8YBi4Ywi9CnwovANE2fYXFwyNhnKW6,XhmT4AZNRKPF7fo2N6xGdecscPTCGvCsPMXm2iziPFBNJt5Qm,29S6KxsHd6ACnRkMsFtvoXLdd7bZraKntBya6UVg6vkdLKBYEo
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "3"
  avago04:
    image: containerman17/subnet-evm-plus:latest
    container_name: avago04
    network_mode: host
    restart: always
    volumes:
      - ~/.avalanchego_04/:/root/.avalanchego
    environment:
      - AVAGO_PARTIAL_SYNC_PRIMARY_NETWORK=true
      - AVAGO_PUBLIC_IP_RESOLUTION_SERVICE=opendns
      - AVAGO_HTTP_HOST=0.0.0.0
      - AVAGO_HTTP_PORT=9010
      - AVAGO_STAKING_PORT=9011
      - AVAGO_TRACK_SUBNETS=hsjD1R3419hb2WpUryiipaVhTTKW37s9BrPi1Rk3eWS1Vc9fr,JD8MbaUp75twdVJ7A4j2ryk7gFJ8FCgQeNLhvDv3y4up9bExp,oAs71UMyGBFs6k5S3NY4NG8FKGnpSbaRhBovS2pckT7C3qzXa,8memoZjjcw3PoJzr8DSUorQkr45DqgEvakLA41tfuj121ziMu,BsiGLLVzkFm8Gbc4B6LqVKhLi68tLWmvavmiTwr2t2s7qZNgB,2tbRjpEFpbCSk5eZF6vXBbpw16jZnJmZok9sEW9HF7oaSGzXca,2LW4YokoP5rLCAaHk4tt85JM8V4qiHc8CWDdG1mGo9FqHFfWAJ,bd4FY16fF5pd7iscMFTtb214Yya1kbrLow1XMyNeb3ZY3fFXA,vGJi918DpSjsjC4DaGfdfgSZTCJQeSfDCzAkdPEwTeQjvjLQX,22JVyUQPXbum5pK9WqC92Qyz9cmwW11MmKXAGn4m3G5TGBvDxd,Eax96S3KFyMs1CpgdmuJjzR1DngU8iKR8j7ugJmx2fvLyANf8,2E51RZFicF5EMNiERg3dySkpcjoz4YaobASeqEdbEpiHsSRHrX,2P3HrSbCPje8AWVDQU3rQLdYcojbnXh4NAAJRYmSC2VzZpWZ6x,2r2fWaWN1pxNrkFzePGzVHc6R9uRuRkn39Gifu5kmQS5U5gn2Y,21Sa545TimmWaJabL4P5hXmaRfTtPxbfjWTHbWYN9E1Ri2AakE,2qJPnDkDH6hn3PVzxzkUdTqDD1HeAnTT8FL4t2BJagc2iuq8j7
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "3"
  avago05:
    image: containerman17/subnet-evm-plus:latest
    container_name: avago05
    network_mode: host
    restart: always
    volumes:
      - ~/.avalanchego_05/:/root/.avalanchego
    environment:
      - AVAGO_PARTIAL_SYNC_PRIMARY_NETWORK=true
      - AVAGO_PUBLIC_IP_RESOLUTION_SERVICE=opendns
      - AVAGO_HTTP_HOST=0.0.0.0
      - AVAGO_HTTP_PORT=9012
      - AVAGO_STAKING_PORT=9013
      - AVAGO_TRACK_SUBNETS=26wQKuvA5kjwrKDaje7nmuJAx6Ke2bGvDDr3EiypNr53rH1pMc,LbvSkGmUJSpUby1gUrk4g9mmdeZQWcVGiFCXv57CJHBrxxEos,29p4FdSKaXQPyw8sqhzJSK37FXuPHdyECau186qZSUNRhk3QuB,2sDjh95i88VY4oi3eACYBxHTY6poZs71yKC71jhzgYBJY5hrCs,2UPuVAx5yFubvDPm6CYywT4mYAdTW3zM1XXD7R7ic8s2zQhF8U,axp7DUSPvFghTM883ug2B8btAReBAACxD1VyENmRDStH4Lfed,hkugVjqegihrQcggCnScNW8yQctyY7Z7oj2Mj5tGxWGXNa5iQ,2W9sERL7Zf7NrWpz7Bzg3fKSEt46gSQaKAU7ntTMSShLy64yMz,oerPWBbtbe13eWbo3AegYUrHuSETeTwyNy7szoHJJ1QQBL9nu,2hoHzxcZktxrTNoqCZhR9bEctc5oCuBqSp6SpRn6uvwxzLkvnD,27mZh9HyNwGdqfkQDWabzo9BonhPSzh1qwdzaDsmPJDn1woCVV,2T4gpnissLkoezQ36XKxhrFAH5yynqKGa1u47XxCYTdfvePuNz,2hZa4RMWAkiQAQ5zpbPSkNziYSHyCqBGeKNnbqWfJL2GKmy8eq,4iDWVgCCSu4Tafpg4bdhxu8q1ap8Rp2hMzG4UPxUhL9UVX6iU,nKJuE11HePLrmp391sfoFVqZR7Fw5VJ1XjyznsogsjebxwiAg,23LsHpx3wTPtNC4PUaTdtNQkaGbLxwiGimnZjHaUc28qLHs7Dn
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "3"
  avago06:
    image: containerman17/subnet-evm-plus:latest
    container_name: avago06
    network_mode: host
    restart: always
    volumes:
      - ~/.avalanchego_06/:/root/.avalanchego
    environment:
      - AVAGO_PARTIAL_SYNC_PRIMARY_NETWORK=true
      - AVAGO_PUBLIC_IP_RESOLUTION_SERVICE=opendns
      - AVAGO_HTTP_HOST=0.0.0.0
      - AVAGO_HTTP_PORT=9014
      - AVAGO_STAKING_PORT=9015
      - AVAGO_TRACK_SUBNETS=yPUx56ffTBML1QfomcBvwfBxfE3LSgqkBNfxTCpx5dr4NNFGB,2kyZRnEHakKriNufphojbeFR5hi247bJeTjFDgQgo7VRRjoqyq,2v7aLktZroWTwcSPHkN6gSDjzJCDuAsHhHpRZTMKiqnegwG6sL,qWeo55RT2F7SNoWtVUuAGptPoz23hViLthjHHaj3BsV2pv7TM,LThVFg2aFviak8Ranf8nNX4UAEtLyzhyCNY2AQdXbgYkJdQTM,eYwmVU67LmSfZb1RwqCMhBYkFyG8ftxn6jAwqzFmxC9STBWLC,2wLe8Ma7YcUmxMJ57JVWETMSHz1mjXmJc5gmssvKm3Pw8GkcFq,yDxaSh2hoVxQKRHmacV1xFpuSgHf6Q6cCMu4v3GoLQnqQWk6L,Cv1gyKNUtPNAtFw8YcjbsD4a3HNRbNvinY7t2gnGK4J54rQK3,nQCwF6V9y8VFjvMuPeQVWWYn6ba75518Dpf6ZMWZNb3NyTA94,2UEGsEEjRyMSgD7cNufCGEXbPXsma7RctBgfRw3Haqkk8oByFa,9ewhue9Lyryt1G4H1icgZotc6wRVwiPgmiVemSN24JXwg91JH,2gHgAgyDHQv7jzFg6MxU2yyKq5NZBpwFLFeP8xX2E3gyK1SzSQ,ii7zCu8JNnYYgPT8PwpVYiTS1gcK5RWJfsyuPXTDv8Bn9wspY,DxanjptkyaeM1eUew2gzUMngHM3n5ttUyMj7BuHw9riXh9pJC,wenKDikJWAYQs3f2v9JhV86fC6kHZwkFZsuUBftnmgZ4QXPnu
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "3"
  avago07:
    image: containerman17/subnet-evm-plus:latest
    container_name: avago07
    network_mode: host
    restart: always
    volumes:
      - ~/.avalanchego_07/:/root/.avalanchego
    environment:
      - AVAGO_PARTIAL_SYNC_PRIMARY_NETWORK=true
      - AVAGO_PUBLIC_IP_RESOLUTION_SERVICE=opendns
      - AVAGO_HTTP_HOST=0.0.0.0
      - AVAGO_HTTP_PORT=9016
      - AVAGO_STAKING_PORT=9017
      - AVAGO_TRACK_SUBNETS=7f9jciLEX25NPJEaAz1X7XF44B1Q9UBwq6PdnCHm5mnUq1e1C,Vn3aX6hNRstj5VHHm63TCgPNaeGnRSqCYXQqemSqDd2TQH4qJ,2QRKgBVT4zbcEWM4aXYRPNRazmas9on1QZodYakh1cF4RDrQE5,2FKZhsPScXjdoAqL6xf9z7Vgqyh3yRpkFFGeLTQfDeQ6JZzyEB,91HAifNFJZq1TaiurGA8jaFGnbA7pkYzJ3kcDSSEJarRwAt56,wuCkRgTHeMZyj7KCiQDpNZoAmFduLx8KRwNxzJYaK7RzVGR6z,2SWquk5bfTpXLrBihfFVLmg4QksBNAuDfFASAZbT2cHmbeaaQv
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "3"
  indexer:
    image: containerman17/indexer-dev:latest
    container_name: indexer
    pull_policy: always
    ports:
      - 80:3000
    restart: always
    volumes:
      - ./indexer_data:/data
    environment:
      - http://65.21.140.118:9002/ext/bc/C/rpc
      - RPC_URL_0=http://65.21.140.118:9006/ext/bc/2tig763SuFas5WGk6vsjj8uWzTwq8DKvAN8YgeouwFZe28XjNm/rpc
      - RPC_URL_1=http://65.21.140.118:9014/ext/bc/2tsFdSeemtqK9vaPgjPrcwvKFKPw1T6PHufaZ26tKbAFSkXPTE/rpc
      - RPC_URL_2=http://65.21.140.118:9014/ext/bc/2PDRxzc6jMbZSTLb3sufkVszgQc2jtDnYZGtDTAAfom1CTwPsE/rpc
      - RPC_URL_3=http://65.21.140.118:9004/ext/bc/2SfshBPqRJexmqdWBY2xYSTq2Rp2dDisuax7nQB6GyNqPjSWWY/rpc
      - RPC_URL_4=http://65.21.140.118:9006/ext/bc/2XCTEc8CfNK9MtQWYMfgNt32QjZsZqq92LH7eTV5xY8YjY44du/rpc
      - RPC_URL_5=http://65.21.140.118:9014/ext/bc/Lgiwfx9L11MLt8RD5Aj7SZ5kEcWQz5NnyCc5hDd5k25J8LoxM/rpc
      - RPC_URL_6=http://65.21.140.118:9004/ext/bc/2vmiAUCfkXd67jEq2GQhzVgTfNs3tpUP89agEEvnRK7urMVpjb/rpc
      - RPC_URL_7=http://65.21.140.118:9006/ext/bc/2c1BN4N9qEhNmW4yCpeLK24SfjFQLyS1Z7FtgRDaYxZWFUUKxf/rpc
      - RPC_URL_8=http://65.21.140.118:9002/ext/bc/J3MYb3rDARLmB7FrRybinyjKqVTqmerbCr9bAXDatrSaHiLxQ/rpc
      - RPC_URL_9=http://65.21.140.118:9004/ext/bc/QgQ2ATB5Ca6US2jur1iPrfBtFDGNSQHXcnSzfv19ZZ2vLZSrk/rpc
      - RPC_URL_10=http://65.21.140.118:9006/ext/bc/2R87vuaaRZRxPLdvdMEpo7fH9qyyNnP34h4nyxuwq8sKkQ1GaE/rpc
      - RPC_URL_11=http://65.21.140.118:9012/ext/bc/hR6djBP7uMGJnXrjdUic2rzvvuuMpqMWNb5us7j8xgmj6Ck2N/rpc
      - RPC_URL_12=http://65.21.140.118:9004/ext/bc/2AB5dDcGsw86kroZ81AZXzdez3CgA1x9uXkyQDhxr98hjrkVhu/rpc
      - RPC_URL_13=http://65.21.140.118:9012/ext/bc/23YwvXVh5LvSX32iMsLWRMYGCNoDLDrZye16i1KQQWZZFb3QzK/rpc
      - RPC_URL_14=http://65.21.140.118:9012/ext/bc/22CN6x5LAPEkvLDdz4UwG3XXtZV69Su3bcspiYtkF9k5f9rcCt/rpc
      - RPC_URL_15=http://65.21.140.118:9006/ext/bc/TT2vQnjSF9VZfjaA5dB1VNKVdqkVCDzSncxaMcGVwYedGaMG3/rpc
      - RPC_URL_16=http://65.21.140.118:9014/ext/bc/22v7AG7h6qaVxd4bLvAsSsg2LZ4RCn5iVYgFn7a2Fj1LCuYwjv/rpc
      - RPC_URL_17=http://65.21.140.118:9012/ext/bc/EJ4DyXHe4ydhsLLMiDPsHtoq5RDqgyao6Lwb9znKhs59q4NQx/rpc
      - RPC_URL_18=http://65.21.140.118:9008/ext/bc/YDJ1r9RMkewATmA7B35q1bdV18aywzmdiXwd9zGBq3uQjsCnn/rpc
      - RPC_URL_19=http://65.21.140.118:9012/ext/bc/HUwWdyoExrb1HgVp5X5sh3AWqhYFnKkfXBfGmGL3qjDsnMoR4/rpc
      - RPC_URL_20=http://65.21.140.118:9014/ext/bc/222KARi6VgSZXbewFp1BvZgyuSKVa9JPb7swhbwN9fUHFKgxUD/rpc
      - RPC_URL_21=http://65.21.140.118:9012/ext/bc/2GRw9HYnCxyVsr4P5pytpqcyRaymtnTuu1oZhuSWcP4DfJxojy/rpc
      - RPC_URL_22=http://65.21.140.118:9010/ext/bc/2L9oVyCkyqMgrwVS7CFkn21KSNWeD67dH6uzjw3LF6ErDhzAjK/rpc
      - RPC_URL_23=http://65.21.140.118:9006/ext/bc/2M47TxWHGnhNtq6pM5zPXdATBtuqubxn5EPFgFmEawCQr9WFML/rpc
      - RPC_URL_24=http://65.21.140.118:9002/ext/bc/2YnwDMW9shSuV6nuYpAhm3DE2KvYJP2GFDvUde6XG8jE5gxvpL/rpc
      - RPC_URL_25=http://65.21.140.118:9012/ext/bc/2cJ7FyNoqigEGoM7m8p4PY7a33B2SQxV8P7VuUVJZ9y5otyqNS/rpc
      - RPC_URL_26=http://65.21.140.118:9002/ext/bc/25xjR3fvh7aXkxs36n1xRc3wLUAuqnS1wBxJD1BC4z3y6mHsEV/rpc
      - RPC_URL_27=http://65.21.140.118:9004/ext/bc/SUDoK9P89PCcguskyof41fZexw7U3zubDP2DZpGf3HbFWwJ4E/rpc
      - RPC_URL_28=http://65.21.140.118:9014/ext/bc/QVbrD172sAF1TgCvN9DZG93nAd2YBGCJVZP4cngdEKCTy2F9v/rpc
      - RPC_URL_29=http://65.21.140.118:9012/ext/bc/2Ec9g5vbwwoy7MEyjmjjEjuS6FzaeToBm1KVbvDU6HeKsSNVTF/rpc
      - RPC_URL_30=http://65.21.140.118:9002/ext/bc/2JepXG35p5i21VxbnPx1eWmu5Z5EutcSXVAtcisBBJPTYzAVmB/rpc
      - RPC_URL_31=http://65.21.140.118:9014/ext/bc/2QGraMRcH8gEnQbLviM4ykgyY31jFfLhaEtEvPHk8q8pPfe7Kj/rpc
      - RPC_URL_32=http://65.21.140.118:9004/ext/bc/8yyXaeqhBEDc7sJVTecGtdHgXE4y2EJD228SaVvEsU6ZU3Kuv/rpc
      - RPC_URL_33=http://65.21.140.118:9008/ext/bc/23aQU1537YseCJmXW11XHjPra6bptBSps5D4xXupt8hN2QUeaG/rpc
      - RPC_URL_34=http://65.21.140.118:9012/ext/bc/25friWasfe2pMdVHQAh5inDBz5XQq42a1V8DYqAGnxeKks5Bkp/rpc
      - RPC_URL_35=http://65.21.140.118:9012/ext/bc/2Xj6iZeySuuUTZR5jYjhQ7yQ84q8AtDWnAJ2vS9BmmXBNJhYD1/rpc
      - RPC_URL_36=http://65.21.140.118:9012/ext/bc/vFHT9J4F6PhqCTMmqkKKUKW3yfsjd6tNvhmcK4MkFa3Pmnnqe/rpc
      - RPC_URL_37=http://65.21.140.118:9012/ext/bc/txbozTNfyRgJJxtHmsbpvwTTWTHU739z7pX7qKdhJVxHC2MAk/rpc
      - RPC_URL_38=https://subnets.avax.network/animalia/mainnet/rpc
      - RPC_URL_39=https://api.avax.network/ext/bc/C/rpc
      - RPC_URL_40=https://subnets.avax.network/beam/mainnet/rpc
      - RPC_URL_41=https://subnets.avax.network/blaze/mainnet/rpc
      - RPC_URL_42=https://subnets.avax.network/blitz/mainnet/rpc
      - RPC_URL_43=https://subnets.avax.network/coqnet/mainnet/rpc
      - RPC_URL_44=https://subnets.avax.network/cx/mainnet/rpc
      - RPC_URL_45=https://subnets.avax.network/delaunch/mainnet/rpc
      - RPC_URL_46=https://subnets.avax.network/dexalot/mainnet/rpc
      - RPC_URL_47=https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc
      - RPC_URL_48=https://subnets.avax.network/etx/mainnet/rpc
      - RPC_URL_49=https://subnets.avax.network/even/mainnet/rpc
      - RPC_URL_50=https://subnets.avax.network/feature/mainnet/rpc
      - RPC_URL_51=https://subnets.avax.network/fifa/mainnet/rpc
      - RPC_URL_52=https://subnets.avax.network/frqtalnet/mainnet/rpc
      - RPC_URL_53=https://subnets.avax.network/goodcare/mainnet/rpc
      - RPC_URL_54=https://subnets.avax.network/gunzilla/mainnet/rpc
      - RPC_URL_55=https://henesys-rpc.msu.io
      - RPC_URL_56=https://subnets.avax.network/highoctane/mainnet/rpc
      - RPC_URL_57=https://subnets.avax.network/innovo/mainnet/rpc
      - RPC_URL_58=https://subnets.avax.network/intersect/mainnet/rpc
      - RPC_URL_59=https://subnets.avax.network/kalichain/mainnet/rpc
      - RPC_URL_60=https://subnets.avax.network/koroshi/mainnet/rpc
      - RPC_URL_61=https://subnets.avax.network/lamina1/mainnet/rpc
      - RPC_URL_62=https://subnets.avax.network/lamina1id/mainnet/rpc
      - RPC_URL_63=https://subnets.avax.network/lucid/mainnet/rpc
      - RPC_URL_64=https://subnets.avax.network/memoria/mainnet/rpc
      - RPC_URL_65=https://subnets.avax.network/numi/mainnet/rpc
      - RPC_URL_66=https://subnets.avax.network/playa3ull/mainnet/rpc
      - RPC_URL_67=https://subnets.avax.network/plyr/mainnet/rpc
      - RPC_URL_68=https://subnets.avax.network/pulsar/mainnet/rpc
      - RPC_URL_69=https://subnets.avax.network/qchain/mainnet/rpc
      - RPC_URL_70=https://subnets.avax.network/shrapnel/mainnet/rpc
      - RPC_URL_71=https://node-api.uptn.io/v1/ext/rpc
      - RPC_URL_72=https://subnets.avax.network/space/mainnet/rpc
      - RPC_URL_73=https://subnets.avax.network/straitsx/mainnet/rpc
      - RPC_URL_74=https://subnets.avax.network/tgp/mainnet/rpc
      - RPC_URL_75=https://subnets.avax.network/tiltyard/mainnet/rpc
      - RPC_URL_76=https://subnets.avax.network/titan/mainnet/rpc
      - RPC_URL_77=https://subnets.avax.network/trx/mainnet/rpc
      - RPC_URL_78=https://subnets.avax.network/zeroonemai/mainnet/rpc
      - DATA_FOLDER=/data
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "3"
